### ISSUE TITLE
Deploy OpenAS2 v2.5.0 to Maven Central

### ISSUE THREAD

**Issue by martinpaoloni** [OpenAS2/OpenAs2App#102]
Hi! Are you planning to do this? Latest version in Central is v2.4.1.

http://search.maven.org/#search|ga|1|openas2

Many thanks!

**Comment by uhurusurfa** [comment]
Yes, I will sort it out in the next few days.

**Comment by NathanNam** [comment]
@uhurusurfa When do you deploy it to Maven Central?

**Comment by NathanNam** [comment]
@uhurusurfa can you share your timeline for the next release of v2.5.0

**Comment by martinpaoloni** [comment]
Hey @uhurusurfa, you still haven't deployed the artifact. :-) When are you planning to do so? Thanks.

**Comment by uhurusurfa** [comment]
@martinpaoloni @NathanNam The 2.6.0 artifacts can be found in Maven Central
