### ISSUE TITLE
Missing documentation on "rename_digest_to_old_name"

### ISSUE THREAD

**Issue by fwiersVANAD** [OpenAS2/OpenAs2App#104]
I discovered that the partnership option

`<attribute name="rename_digest_to_old_name" value="true"/>`

solved a communication problem with a partner (Seeburger, older version). 

It would have saved me a lot of time if this option was mentioned in the manual at either chapter 13 "Troubleshooting OpenAS2" or chapter 14 "Partner AS2 Compatibility Settings".

**Comment by uhurusurfa** [comment]
I will add it to the compatibility settings. Thanks for the feedback

**Comment by uhurusurfa** [comment]
Added to compatibility settings in documentation
