### ISSUE TITLE
BUG REPORT-DbTrackingModule "tcp_server_start" params ineffective

### ISSUE THREAD

**Issue by qq379673328** [OpenAS2/OpenAs2App#110]
file "EmbeddedDBHandler.java" line 41 nearby:
<code>
   if ("true".equalsIgnoreCase(getParameter(PARAM_TCP_SERVER_START, "true")))
</code>
should be
<code>
  if ("true".equalsIgnoreCase(params.get(PARAM_TCP_SERVER_START))) 
</code>

**Comment by uhurusurfa** [comment]
The second parameter is the default value if the lookup for the
PARAM_TCP_SERVER_START parameter returns NULL.
Therefore unless the PARAM_TCP_SERVER_STARTparmeter is set to something
else other than "true" it will always return true which is the desired
effect in this case.

**Comment by uhurusurfa** [comment]
You are correct, it should use the params.get() accessor because the class
does not have its own config definition in the XML so needs it passed in.

I will fix and will be available in the next release.

Thanks for pointing out the bug.
