### ISSUE TITLE
Setting dynamic attribute from filename , getting null value

### ISSUE THREAD

**Issue by irikeish** [OpenAS2/OpenAs2App#116]
I have tried using your given example, to set a dynamic subject but it gives me null. 

```
<attribute name="attribute_names_from_filename" value="X-attribute1,Y-attribute2"/>
 			<attribute name="attribute_names_regex_on_filename" value="([^-]*)-([^.]*).txt"/>
 			<attribute name="subject" value="Target product: $attributes.X-attribute1$ Sequence Count:
$attributes.Y-attribute2$"/>
```

filename: abc-23.txt
I have tried using regex = "([^.]*)-([^.]*).txt"
same output attribute  value in subject is null.

**Comment by uhurusurfa** [comment]
Aplogies but the example has a mistake in it.

The correct attribute name should be "attribute_values_regex_on_filename" not "attribute_names_regex_on_filename"

**Comment by irikeish** [comment]
I have tried changing it, but it gives me the same output.

**Comment by uhurusurfa** [comment]
I have tested with these on Linux, Unix and OSX on Java 8 and Java 10 and works fine:

<attribute name="attribute_names_from_filename" value="X-attribute1,Y-attribute2"/>
 <attribute name="attribute_values_regex_on_filename" value="([^-]*)-([^.]*).txt"/>
 <attribute name="subject" value="Target product: $attributes.X-attribute1$ Sequence Count: $attributes.Y-attribute2$"/>

**Comment by uhurusurfa** [comment]
Ah.... the MDN subject will not currently work using that mechanism. The filename parsing is done before the original filename is extracted from the payload.
I will fix this in the next release.

**Comment by uhurusurfa** [comment]
Release 1.6.1 just made available fixes this for you

**Comment by SaiKrishna03** [comment]
I checked with your latest release.
receiver side i got the correct subject in mdn message but still in sender side I am getting the below mdn message,
**Subject: Target product: null Sequence Count:null**
why?

**Comment by uhurusurfa** [comment]
I do not undeerstand your issue. Please provide more information

**Comment by SaiKrishna03** [comment]
dynamic subject
**<attribute name="attribute_names_from_filename" value="X-attribute1,Y-attribute2"/>
<attribute name="attribute_values_regex_on_filename" value="([^-]*)-([^.]*).txt"/>
<attribute name="subject" value="Target product: $attributes.X-attribute1$ Sequence Count:$attributes.Y-attribute2$"/>**

file name - **atish-sai.txt**

Receiver side subject in mdn message
**Subject: Target product: atish Sequence Count:sai**

sender side subject in mdn message
**Subject: Target product: null Sequence Count:null**
why?

**Comment by SaiKrishna03** [comment]
partenship configuration
[partnerships.txt](https://github.com/OpenAS2/OpenAs2App/files/2366381/partnerships.txt)

config file
[config.txt](https://github.com/OpenAS2/OpenAs2App/files/2366389/config.txt)

mdn file got back by sender
[atish-sai - Copy.txt](https://github.com/OpenAS2/OpenAs2App/files/2366393/atish-sai.-.Copy.txt)

mdn in receiver side
[atish-sai - Copy.txt](https://github.com/OpenAS2/OpenAs2App/files/2366394/atish-sai.-.Copy.txt)

**Comment by uhurusurfa** [comment]
The only way this can happen is if the OpenAS2  server receiving the MDN (ie.Atish)  is running a prior version of OpenAS2 before 2.6.1

IMPORTANT NOTE: You cannot simply rename a jar file to some other name and leave it in the classpath of the Java environment and the copy a new version of the jar into the classpath - you will have unstable behaviour.

I strongly suggest you do CLEAN installs for your "Sai" and "Atish" instances and try the test again.

I have run all the tests yet again using OpenAS2A and OpenAS2B as partners as in the default config both as a single instance of OpenAS2 and as separate instances (one for OpenAS2A and one for OpenAS2B)  but cannot replicate and therefore can do no more on this issue

**Comment by uhurusurfa** [comment]
As a test, if you remove the "subject" attribute for the "Sai" server it should return the subject received from the sender of the AS2 message (Atish) with the string:

> Your Requested MDN Response re: Subject: Target product: atish Sequence Count:sai
