### ISSUE TITLE
Content-Transfer-Encoding always set to base64

### ISSUE THREAD

**Issue by jsmucr** [OpenAS2/OpenAs2App#120]
I tried to upgrade from v2.4.3 to v2.5.0 and my OpenAS2 instance stopped communicating with our Mendelson AS2, the latter showing this in logs:
```
[10:37:40 AM] Data has arrived that could not be processed because it contains errors. The defined content transfer encoding "base64" is unknown.
[10:37:40 AM] LogAccessDB.log: integrity constraint violation: foreign key no parent; SYS_FK_10110 table: MESSAGELOG
[10:37:40 AM] UNKNOWN: Generating outbound MDN, setting message id to "mendAS2-1536741460814-3798@unknown_unknown".
[10:37:40 AM] mendAS2-1536741460814-3798@unknown_unknown: Outbound MDN created for AS2 message "UNKNOWN", state set to [processed/error: unexpected-processing-error].
[10:37:40 AM] LogAccessDB.log: integrity constraint violation: foreign key no parent; SYS_FK_10110 table: MESSAGELOG
[10:37:40 AM] UNKNOWN: Outbound MDN details: BASE64Decoder: Error in encoded stream: needed at least 2 valid base64 characters, but only got 0 before padding character (=), the 10 most recent characters were: "&\249\147\241h\214\21x\133="
[10:37:40 AM] LogAccessDB.log: integrity constraint violation: foreign key no parent; SYS_FK_10110 table: MESSAGELOG
[10:37:40 AM] AS2ServerProcessing: [java.lang.RuntimeException] Unexpected MDN received: No related message exists for inbound MDN "UNKNOWN"
```
As I've discovered later, a new header, `Content-Transfer-Encoding`, has appeared in the outgoing messages. The problem is that this header is set to `base64`, no matter the partnership settings, while the body is kept binary even if I set the `content_transfer_encoding` partnership attribute to `base64`.

Capturing the loopback communication during tests reveals that this issue is present even in the latest version (v2.6.1):

[v2.4.1 HTTP request](https://github.com/OpenAS2/OpenAs2App/files/2378399/2.4.1.txt)
[v2.6.1 HTTP request](https://github.com/OpenAS2/OpenAs2App/files/2378398/2.6.1.txt)

**Comment by jsmucr** [comment]
I've discovered a workaround. It is necessary to set the `content_transfer_encoding` attribute to `binary`. See this:

    protected String getEncoding(String contentTxfrEncoding)
    {
        // Bouncy castle only deals with binary or base64 so pass base64 for 7bit, 8bit etc
        return "binary".equalsIgnoreCase(contentTxfrEncoding) ? "binary" : "base64";
    }

But for some reason the `base64` encoding does not work and thus going with `binary` is the only option.

**Comment by uhurusurfa** [comment]
The Content-Transfer-Encoding is actually not required and really does not matter what you set it to since it is not used in HTTP:
https://tools.ietf.org/html/rfc4130#section-5.2
It seems the header is only relevant to MIME compliant protocols and must reflect the encoding of the body part being sent. (https://tools.ietf.org/html/rfc2616#section-19.4.5)
The current implementation of OpenAS2 sets the Content-Transfer-Encoding header to the encoding of the outermost mime body part and this will always be BASE64 if using encryption, compression or signing. The base mime body part that encapsulates the initial file to be transferred uses the defined transfer encoding. The signing, encryption and compression each encapsulate the passed in mime body part into a new mime body part so effectively there are up to 4 mime body parts in wrapped inside each other to send a message. So the "Content-Transfer-Encoding" setting in the config only applies to the innermost mime body part. Since each mime body part stores it's "Content-Transfer-Encoding" in the body part headers there is no sense in sending it in the HTTP headers.
Considering the above and specifically the RFC4130 statement, I will probably add a config option to make setting the header in the HTTP headers optional  in the next release.

**Comment by jsmucr** [comment]
I don't really understand your point. Let me quote.
> OpenAS2 sets the Content-Transfer-Encoding header to the encoding of the outermost mime body part and this will always be BASE64 if using encryption, compression or signing.

It's binary, not base64. See the requests I attached in the post above. Maybe you mean that it's encoded to base64 and *then* encrypted? Isn't it expected to be the other way around?

And from https://tools.ietf.org/html/rfc4130#section-5.2.1
> a content transfer encoding value of binary or 8-bit is permissible but not required

This pretty much says that the header of value `base64` is not meant to be there. Only `8bit` (broken, turns into `base64`) or `binary`.

**Comment by uhurusurfa** [comment]
Basically it depends on whether the HTTP header "Content-Transfer-Encoding" is intended to refer to the HTTP body content or the original body content of the file being transferred - it is not clear to me from the AS2 spec..
The HTTP header in OpenAS2 is set using [mimebodypart].getEncoding() ... which return the encoding of the outermost mime body part.
The default encoding for AS2 spec is "binary" and in OpenAS2,  if there is no content_transfer_encoding attribute then it is set to "binary" nd it is only the initial encapsulation of the file to transfer in a mime body part that has a content transfer encoding that will match anything set in the config.

So the alternative approach is to set the HTTP header to whatever the content_transfer_encoding attribute is set to or the default of "binary" if not set.... irrespective of the encoding of the outermost  mime body part.

**Comment by jsmucr** [comment]
I'd hold to the specification of the header itself (since the specification isn't overridden by anything in RFC 4130). RFC 1521 says:
>The Content-Transfer-Encoding field is used to indicate the type of transformation that has been used in order to represent the body in an acceptable manner **for transport**.

and
>  If the **body** contains binary data, the "binary" Content-Transfer-Encoding token must be used.

To me this says clearly that this header relates to the whole body, not any of its parts individually, and must be set to `binary` if the body's binary.

Also see this example building an AS2 message with `Content-Transfer-Encoding: base64`: https://notebookbft.wordpress.com/2017/12/11/as2-protocol-for-business-data-interchange-via-http-part-2/
The result body is base64, not binary.

**Comment by uhurusurfa** [comment]
Note that RFC1521 is about MIME not about HTTP and as such refers to the mime headers not the HTTP headers.
Since  Content-Transfer-Encoding is not used in HTTP it can only be relevant to mime processing.
It is unclear to me why the header is even mentioned in the spec for AS2 since the  Content-Transfer-Encoding is part of the mime headers anyway and ultimately the correct source of truth for how the mime body part is encoded.

BASE64 is a character based encoding represents binary data in an ASCII string format so it will work with any stream of data.
OpenAS2 ignores that header and simply processes the message unravelling the encryption, signing and compression using the mime headers. Mendelson AS2 for whatever reason chooses to check that the header is set to one of "binary" or "8bit" but does not actually use that value to unravel the message.

**Comment by jsmucr** [comment]
Mendelson AS2 does not only check it. It uses it to decode the body via `javax.mail.internet.MimeUtility`. The exact exception was:
```
com.sun.mail.util.DecodingException: BASE64Decoder: Error in encoded stream: needed at least 2 valid base64 characters, but only got 0 before padding character (=), the 10 most recent characters were: "/\243ok\173\176\213\146\132="
```

The message in the first post that Mendelson programmers used in place of **an** exception is not related to the problem.

RFC1521 might be about MIME but that's where the header is defined. If it's not supposed to be used in HTTP then why use it anyway? Since I saw some requests from other users, I know that there have been issues with some clients requiring the header in HTTP. But this *improvement* ultimately hurts compatibility with others.

So what I suggest is to drop the header completely (and maybe set it on demand to an user defined value) or set it to whatever the body truly is, not to whatever is specified somewhere inside the body.

If you decide to keep it the way it is I will no longer complain. 😄 However, I'm searching for an actively developed Mendelson AS2 replacement for more than 50 partners (and counting, fast) using very wide set of clients and the less workarounds I'll need to use to bring it into production the better.

**Comment by uhurusurfa** [comment]
Ultimately I do not mind adding a variety of solutions to the same problem
as long as they are configurable and backwards compatible.
My experience with AS2 is that every vendor seems to have some aspect where
their interpretation of the spec is different to others and that is why
there are so many config options in OpenAS2.
Make your solution configurable via a partnership attribute and I will
merge it.

Note that there is a method on the partnership for attribute lookup at
partnership level and then look at system level as well (properties)  if no
partnership attribute is found. This allows changing the system default by
setting a system property with partner level override. Method name is
getAttributeOrProperty

**Comment by jsmucr** [comment]
Will do. :)

**Comment by dks-ait** [comment]
On the sender side : Even after encrypting I can see body as the binary only, its never base64 encoded. The internal signature surely is base64 encoded - but the post-encryption body is just binary DER. 

If we send base64 encoded data on the receiver side, we get error as OpenAs2 tries to read that data as binary DER. I hope that is what Jan is also suggesting in his posts. Please do let us know if there is a plan to support that in near future. We are hitting this issue. Is there any configuration that we are missing to instruct OpenAS2 to decode base64 first and then start reading the ASN1 from decoded DER data.

**Comment by uhurusurfa** [comment]
Note that the latest version seems to be working for many users now and if you are not running the latest version then I suggest you upgrade but be sure to read the release notes when you do.

It is not clear to me exactly what you are doing but OpenAS2 decrypts based on what is in the headers of the mime body parts received from the sender.  
On the sender side, those headers are added automatically by the BouncyCastle libraries and is not controlled by OpenAS2. OpenAS2 simply invokes the BouncyCastle classes that do the signing/encryption passing a preferred algorithm in the call. If you set the "content_transfer_encoding" attribute on the partnership, the OpenAS2 code base will pass either "binary" or "base64" to the initial input to the the encryption and signing process and bouncy castle will set the headers to whatever algorithm it actually uses.

**Comment by uhurusurfa** [comment]
Note that the latest version seems to be working for many users now and if you are not running the latest version then I suggest you upgrade but be sure to read the release notes when you do.

It is not clear to me exactly what you are doing but OpenAS2 decrypts based on what is in the headers of the mime body parts received from the sender.  
On the sender side, those headers are added automatically by the BouncyCastle libraries and is not controlled by OpenAS2. OpenAS2 simply invokes the BouncyCastle classes that do the signing/encryption passing a preferred algorithm in the call. If you set the "content_transfer_encoding" attribute on the partnership, the OpenAS2 code base will pass either "binary" or "base64" to the initial input to the the encryption and signing process and bouncy castle will set the headers to whatever algorithm it actually uses. So in a setup using encryption and signing it will use whatever algorithm is defined in "content_transfer_encoding" to encrypt and the encrypted body part is passed in to the signing process and BouncyCastlke chooses the algorithm. Note that if you are using compression it will probably always look like binary if you look at the compressed body part.
