### ISSUE TITLE
tcp_server_password attrib on DBTrackingModule does nothing

### ISSUE THREAD

**Issue by sdgathman** [OpenAS2/OpenAs2App#125]
Instead, it seems to use db_pwd.   As a consequence, installing on Fedora and starting the server lets the world connect to 9092 and issue DB commands - even create files named ../anydir/anyname.mv.db as openas2 user.

One solution for me as a packager is to create the database at first startup (no existing db) with the password in config.xml - and exiting with an error if it is the factory password.

**Comment by sdgathman** [comment]
It would also help if tcp_server could listen on localhost only.  Maybe I missed a way to do that.

**Comment by sdgathman** [comment]
The Fedora server install blocks incoming ports by default, but the workstation install allows unprivileged incoming ports by default.

**Comment by uhurusurfa** [comment]
The code for staring the server is here:
https://github.com/OpenAS2/OpenAs2App/blob/dev/Server/src/main/java/org/openas2/processor/msgtracking/EmbeddedDBHandler.java#L38

As you can see it does use the tcp_server_password attribute.

I can add a parameter that will not allow creating a new DB - it will rely on there being a DB already created (-ifExists ).
I can add the option to start the TCP server so that you can only connect to it from localhost.
Not seen a mechanism to bind it to a specific IP so far. (exclude the -tcpAllowOthers option)

**Comment by uhurusurfa** [comment]
Try passing this system property to bind to s specific IP address: http://www.h2database.com/html/advanced.html#server_bind_address

**Comment by sdgathman** [comment]
I wonder if I can just set tcp_server_start = "false" for the default config?  (And still have a ready-to-run server.)

**Comment by sdgathman** [comment]
Yes, setting tcp_server_start = "false" allows message exchange without exposing the tcp_server to the public with factory password.  So that might be a good option for the package defaults.

**Comment by sdgathman** [comment]
Ok, OpenAS2 also listens on 14321 by default with a factory password.  I need to adjust the default config so a naive user is not exposing a SocketCommandProcessor to the internet with a factory password without realizing it.  But also having OpenAS2 Just Work™ with the default config (which it does at present with OpenAS2A and OpenAS2B partners preconfigured - very helpful for beginners).

**Comment by sdgathman** [comment]
Is there a class I could call from command line to extract key attributes like db_pwd from the config?  I could refuse to start until the admin changes the factory password, then init the database (if it doesn't exist) using the configured password.  Currently, it ships a pre-initialized database with a factory password.

Sure, I could grep for db_pwd= and parse the line in bash, but I'd feel better with something less hacky and fragile.

**Comment by uhurusurfa** [comment]
The TCP server password is only for starting and stopping the TCP server.

**Comment by uhurusurfa** [comment]
One option is to start the DB that comes with the install package and change the password as part of the install process but would have to write that back to the config obviously.

**Comment by sdgathman** [comment]
I only need to *read* the config when starting the install DB to change the password to what was configured.

**Comment by sdgathman** [comment]
The recommended solution in OpenAS2 HowTo doc is to comment out the SocketCommandProcessor module.  I will change the Fedora package to have it commented out by default.  

I have an unrelated problem I can't find the solution to: while org.openas2.remote.CommandLine connects to the SocketCommandProcessor on port 14321, I can't seem to actually run any commands.  I can't find any docs on what could be the problem.  The exception is:
```
Enter command: cert
javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1551)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:95)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at org.openas2.remote.CommandLine.main(CommandLine.java:71)
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at sun.security.ssl.Handshaker.activate(Handshaker.java:529)
	at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1492)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1361)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:757)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at java.io.PrintStream.write(PrintStream.java:480)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
	at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
	at java.io.PrintStream.write(PrintStream.java:527)
	at java.io.PrintStream.print(PrintStream.java:669)
	at java.io.PrintStream.println(PrintStream.java:806)
	at org.openas2.remote.CommandLine.main(CommandLine.java:68)
```

**Comment by uhurusurfa** [comment]
Check section 16: Remote Control in the OpenAS2HowTo - specifically the
last 2 paragraphs.

**Comment by sdgathman** [comment]
The client and the server are both running on the same machine (and I've also tried different machines with the same OS).  Both ends have the same libraries.  I did in fact read section 16 long before reporting the problem.  Maybe this needs to be a new issue.

**Comment by uhurusurfa** [comment]
Turn on SSL debugging on the server side to see what the server thinks is wrong (add this to the startup script of the oOpenAS2 server: -
-Djavax.net.debug=SSL. 
The output in your previous post from the remote client is typical of situations where the server cannot support the protocol requested but could be something else.

**Comment by sdgathman** [comment]
With SSL debug, it says "Ignoring disabled cipher suite:" for every cipher suite supported by Java.  That would explain why SSL doesn't work.  Maybe there is another package I need to install for SSL to work on Fedora.

BTW,  all *my* admin connections to openas2 are over VPN (Cjdns IP6 mesh VPN), which already provides the equivalent of SSL via authenticated IPs and end-to-end encrypted sessions.  So it would be useful to simply allow plain TCP connections.  However, I still need to get SSL working in the Fedora package for more general applications.

**Comment by uhurusurfa** [comment]
Download this file: 
https://confluence.atlassian.com/stashkb/files/679609085/679772359/1/1414093373406/Ciphers.java

Or of you prefer not to click the link here is the code:
`import java.util.Iterator;
import java.util.Map;
import java.util.TreeMap;
import javax.net.ssl.SSLServerSocketFactory;

public class Ciphers
{
    public static void main(String[] args)
        throws Exception
    {
        SSLServerSocketFactory ssf = (SSLServerSocketFactory)SSLServerSocketFactory.getDefault();

        String[] defaultCiphers = ssf.getDefaultCipherSuites();
        String[] availableCiphers = ssf.getSupportedCipherSuites();

        TreeMap ciphers = new TreeMap();

        for(int i=0; i<availableCiphers.length; ++i )
            ciphers.put(availableCiphers[i], Boolean.FALSE);

        for(int i=0; i<defaultCiphers.length; ++i )
            ciphers.put(defaultCiphers[i], Boolean.TRUE);

        System.out.println("Default\tCipher");
        for(Iterator i = ciphers.entrySet().iterator(); i.hasNext(); ) {
            Map.Entry cipher=(Map.Entry)i.next();

            if(Boolean.TRUE.equals(cipher.getValue()))
                System.out.print('*');
            else
                System.out.print(' ');

            System.out.print('\t');
            System.out.println(cipher.getKey());
        }
    }
}`
Compile it: 
`javac Ciphers.java`
Then run using this:

 `java Ciphers | grep -i anon`

Choose any one of the ciphers that appear in the output from the last command and configure the remote client to use it.

**Comment by sdgathman** [comment]
None of the ciphers are anon.

```
$ java Ciphers
Default	Cipher
 	SSL_RSA_WITH_NULL_SHA
*	TLS_DHE_RSA_WITH_AES_128_CBC_SHA
*	TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
*	TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
*	TLS_DHE_RSA_WITH_AES_256_CBC_SHA
*	TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
*	TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
*	TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
*	TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
*	TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
*	TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
*	TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
*	TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
 	TLS_ECDHE_ECDSA_WITH_NULL_SHA
*	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
*	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
*	TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
*	TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
*	TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
*	TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
 	TLS_ECDHE_RSA_WITH_NULL_SHA
*	TLS_EMPTY_RENEGOTIATION_INFO_SCSV
*	TLS_RSA_WITH_AES_128_CBC_SHA
*	TLS_RSA_WITH_AES_128_CBC_SHA256
*	TLS_RSA_WITH_AES_128_GCM_SHA256
*	TLS_RSA_WITH_AES_256_CBC_SHA
*	TLS_RSA_WITH_AES_256_CBC_SHA256
*	TLS_RSA_WITH_AES_256_GCM_SHA384
 	TLS_RSA_WITH_NULL_SHA256
```

**Comment by uhurusurfa** [comment]
Ok so probably your system has the value of the *jdk.tls.disabledAlgorithms*
security property In the java.security file set to disable insecure ciphers.

I will work on supporting self signed certificates and let you know as a
short term solution. In the near term I will create  a REST API to support
remote control.

**Comment by uhurusurfa** [comment]
The cipher issue is tracked here: https://github.com/OpenAS2/OpenAs2App/issues/133
