### ISSUE TITLE
How to use one open AS2 for multiple Partners multiple Certificates

### ISSUE THREAD

**Issue by zengxw08** [OpenAS2/OpenAs2App#128]
How to use one open AS2 for multiple Partners multiple Certificates

**Comment by uhurusurfa** [comment]
Read the OpenAS2HowTo.pdf that came with the downloaded zip of the application. 

There is detailed information on that exact question.

**Comment by zengxw08** [comment]
thank you very much，I found it，but I may describe the error about this issue。
