### ISSUE TITLE
Default value as2_mdn_response_max_wait_seconds might be too low

### ISSUE THREAD

**Issue by fwiersVANAD** [OpenAS2/OpenAs2App#129]
An AS2 partner of ours sends (retries) async MDNs after a 5 minute time-out. This gives rise to errors since OpenAS2 removes "pending MDNs" after 5 minutes.

If retries after 5 minutes is a common case (I'm not sure), I think it would be better to set the default value of the related property as2_mdn_response_max_wait_seconds to 16 minutes so the other party gets 3 attempts without causing errors on the OpenAS2 side.

**Comment by uhurusurfa** [comment]
Sounds reasonable. Have changed and will be 16 minutes in the next release.
