### ISSUE TITLE
Git sources not properly tagged for v2.6.4

### ISSUE THREAD

**Issue by DevDef** [OpenAS2/OpenAs2App#134]
Hi Christopher,

I’m trying to build an RPM for version 2.6.4 with an automatic fetching of the Git sources. I use the following in my spec file:
```specfile
Version: 2.6.4
Source0: https://github.com/OpenAS2/%{project_name}/archive/v%{version}/%{name}-%{version}.tar.gz
```
But the pom.xml file is still having 2.6.3 as the OpenAS2 version, and it makes the RPM build fail. I think that you forgot to tag the files as v2.6.4.
See: https://github.com/OpenAS2/OpenAs2App/compare/v2.6.4...master

Could you fix it please?

TIA,

Davy

PS: BTW, I wonder why bcpg is not on par with other bc libs (1.54 vs 1.59)…

**Comment by uhurusurfa** [comment]
Thanks for notifying me - that should be fixed now.

**Comment by DevDef** [comment]
Confirmed. Thank you. :-)
