### ISSUE TITLE
Customization of the message tracking table name

### ISSUE THREAD

**Issue by DevDef** [OpenAS2/OpenAs2App#143]
Hi Chris,

When using an external database server like MySQL, it would be interesting to be able to customize the name of the message tracking table (for example, to fit a naming policy). I propose to add a new config parameter as an XML attribute named “db_table”. That’s something Luc has already implemented in [his fork](https://github.com/lucguinchard/OpenAs2App).

**Comment by uhurusurfa** [comment]
Sounds like a good idea. Feel free to raise a pull request yourself if you want otherwise I will do it in a next release

**Comment by DevDef** [comment]
Almost ready to merge #149, but needs testing…
Please read the important comment.

**Comment by DevDef** [comment]
I think it could be merged now.

**Comment by uhurusurfa** [comment]
🚀 Thanks for the work. Have merged and closing this issue
