### ISSUE TITLE
Need MDN signatures

### ISSUE THREAD

**Issue by sdgathman** [OpenAS2/OpenAs2App#154]
Please reopen #57, or move discussion here.  It should not be necessary for OpenAS2 to store the raw messages ("documents"), as the business system will/should do so.  OpenAS2 stores the MDN text, which includes the MIC of the document - but does not store the MDN signature.  

Storing the raw MDN is one way to do that.  However, each pkcs7 sig includes the signing cert - which is the same most of the time - and the signature can be detached.  So the MDN could be parsed into the MDN text (currently stored), a reference to the signing cert, and the detached signature.

The ultimate goal, is that given e.g. a raw EDI invoice from the business system, some tool can recompute the MIC, use the MIC as a key to lookup the MDN with attached or detached signing cert and signature, and verify the signature.   Then print out all four components.

**Comment by uhurusurfa** [comment]
Feel free to implement a solution and rais a pull request.

**Comment by sdgathman** [comment]
I'll do my best as time allows.  I think the first step is to store the raw MDNs, and then worry about parsing them to optimize the storage.  I'll check if the document MIC is currently a column in the MDN database log.  That would make finding the required MDN a cinch.

**Comment by uhurusurfa** [comment]
Please develop it as a plugin module that can be configured in config.xml

**Comment by sdgathman** [comment]
I was going to modify MDNFileModule.

**Comment by sdgathman** [comment]
> The boilerplate disclaimer text is not worth much.
I shouldn't be too quick to say that.  Maybe there is a use case I'm not aware of.

**Comment by sdgathman** [comment]
The MDN database log does not current include MIC, so the only way (although a reasonably good way) to find the MDN for a document (message) is a text search of the MDN text.

A simple format for the raw MDNs would be:
```
MIC: /YFJ+ZIbzXyRfFBDDGpgVFGHlR5UJmKrPXd6VwhIFwo=, SHA256
-----BEGIN PKCS7-----
MIIJMgYJKoZIhvcNAQcCoIIJIzCCCR8CAQExCzAJBgUrDgMCGgUAMAsGCSqGSIb3
DQEHAaCCBXUwggVxMIIEWaADAgECAgkA0pvl9IhyaZ8wDQYJKoZIhvcNAQELBQAw
ZDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExDzANBgNVBAcMBk94
...
hCq27aEA
-----END PKCS7-----
```
That allows a search for the MDN given a document using the unix tools (and Windows too these days).  It is not required often, so it doesn't have to be super fast.

**Comment by sdgathman** [comment]
I don't think OpenAs2 saves enough info to check whether a message has an MDN - even without a signature.  I think you need msgheaders for the original message - at least when the include-headers option is used.  I think the MIC in the saved MDNs is for the original message with headers - but I can't be sure, because the headers are gone.
