### ISSUE TITLE
Unidirectional partnership configuration

### ISSUE THREAD

**Issue by jarretttaylor** [OpenAS2/OpenAs2App#155]
In OpenAS2HowTo.pdf, the section entitled **7. Partner Configuration**, there is a note that says "**It is necessary to have 2 elements even if data transfer is unidirectional.**"
Is this meant to imply that even if I am only receiving transfers from other entities, I still need to configure two partnerships to define the relationship? A configuration example follows:

```
<partner name="MyCompany" as2_id="MyCompany_OID" x509_alias="mycompany" email="as2msgs@openas2.com"/>

<partner name="PartnerA" as2_id="PartnerA_OID" x509_alias="partnera" email="as2msgs@partnera.com"/>

<partnership name="PartnerA-to-MyCompany">
    <sender name="PartnerA"/>
    <receiver name="MyCompany"/>
</partnership>

<!-- Is this needed if my intent is only to receive from PartnerA? -->
<partnership name="MyCompany-to-PartnerA">
    <sender name="MyCompany"/>
    <receiver name="PartnerA"/>
</partnership>
```

**Comment by uhurusurfa** [comment]
That is no longer true. The need for the definition of a partnership in
both directions was removed in 2.9.0 but the documentation was not updated.

**Comment by jarretttaylor** [comment]
Thanks for the clarification.
