### ISSUE TITLE
Onetime code style/formatting change

### ISSUE THREAD

**Issue by VboxNick** [OpenAS2/OpenAs2App#172]
Hi All,

For consistency reasons I would like to propose to format code  without any changes in terms of functionality or behavior. 

What do you think?

Any ideas, suggestions, comments are welcome.

@uhurusurfa @igwtech

**Comment by uhurusurfa** [comment]
@VboxNick  @igwtech I
Nick - I am happy for you to do a one time major reformat with no code changes.
If Javier has no outstanding code then you can go ahead and execute the change now.

**Comment by igwtech** [comment]
@VboxNick,
  Nick, Go ahead. Can you include styling checks using checkstyle in the
pom.xml so future commits maintain the same styling guidelines?

-J

**Comment by VboxNick** [comment]
@igwtech sure. It will be part of the build.
