### ISSUE TITLE
Log files are not generating inside Docker image

### ISSUE THREAD

**Issue by soonuu** [OpenAS2/OpenAs2App#200]
We tired the new image,uploaded in https://github.com/OpenAS2/OpenAs2App/pull/198 . Mounted the Logs folder also checked with docker console, logs folder is still empty . No log file is generating.

**Comment by soonuu** [comment]
#198 #197 Config file is also attached , using FileLogger for logging. 
[config.xml.txt](https://github.com/OpenAS2/OpenAs2App/files/5268204/config.xml.txt)

**Comment by uhurusurfa** [comment]
This is not an OpenAS2 issue. Closing.
