### ISSUE TITLE
Monitor changes of config.xml file

### ISSUE THREAD

**Issue by neesonqk** [OpenAS2/OpenAs2App#239]
Hi thank you for making this great APP.

Understand that currently this `config.xml` is not monitored and will need a restart, after reviewed the code I feel it's not so difficult to make it happen, because `config.xml` is cached during startup, the simplest way is to recache it once changes detected, we can't just do a reload of the file, this might corrupt some on-going executions, in my mind, the key points to perform a recache are:

1. Stop processing queued message(s).
2. Wait for all running tasks (like on-going sending and receiving tasks) to be finalised.
3. Stop Active Modules.
4. Reload `config.xml` to `cfg` object
5. Start modules which stopped at step 3
6. Resume queue processing.

I'm not very sure if any other conflicts that should be taken into consideration.

It brings a lot of conveniences to make it re-cacheable, for example, we have multiple polling modules defined and get modified from time to time, for now we have to stop and do a restart.

What do you think?

Cheers!

**Comment by uhurusurfa** [comment]
The directory polling directories will be moved to the partnership and so will leave just core config in config.xml so I will not be making the suggested change to auto reload config.xml
If there are other reasons that an auto reload would make sense let me know and I might consider it.

**Comment by neesonqk** [comment]
Yes, it makes more sense to move polling directory to partnership, other than pooling directory there isn't any other config need to be reloaded, in fact we have implemented a temp way to make it reloads only the polling directories for now, will keep an eyes on here, and hope can help when moving polling directory to partnership. Thank you!
