### ISSUE TITLE
Update of log4j lib

### ISSUE THREAD

**Issue by fraucs** [OpenAS2/OpenAs2App#249]
Hi, can you update the library into `Server/src/resources/db/ddlutils-lib/log4j-1.2.8.jar` ?

**Comment by uhurusurfa** [comment]
The issue is with log4j 2 not the old version 1 log4j.
Additionally, that library is only used to generate the DDL file - not used by OpenAS2 server.

**Comment by fraucs** [comment]
you're right, sorry for the nonsense I wrote.
