### ISSUE TITLE
MDN Response logging shows as Java object instead of the message string

### ISSUE THREAD

**Issue by uhurusurfa** [OpenAS2/OpenAs2App#253]
I'm sending some messages using OpenAS2 and receiving the corresponding MDNs with success but when I look into the stored received MDN files (and the mdn_response field in the db), instead of the text received in the MDN, it shows something like:

...
DISPOSITION: automatic-action/MDN-sent-automatically; processed
Text:
java.io.ByteArrayInputStream@76182f20

and it shows the same in the db mdn_response field:

    java.io.ByteArrayInputStream@76182f20

**Comment by pkraeutli** [comment]
I suspect this happens here: https://github.com/OpenAS2/OpenAs2App/blob/master/Server/src/main/java/org/openas2/util/AS2Util.java#L132
I will try to verify if this is the case.

**Comment by pkraeutli** [comment]
Looks like it:
<img width="790" alt="Screenshot 2022-02-02 at 09 10 36" src="https://user-images.githubusercontent.com/886082/152118976-458bc384-1773-43e5-82ac-19b75894bfbc.png">
