### ISSUE TITLE
Misleading error message when partnership/receiver is missing

### ISSUE THREAD

**Issue by akasparas** [OpenAS2/OpenAs2App#255]
I had recipient tag instead of receiver in my partnership configuration. Yet OpenAS2 complained that sender is missing. Spent way too much time trying to find what's wrong.

https://github.com/OpenAS2/OpenAs2App/blob/3d566b06493b44b23e3dbb13272f3efed2ab2687/Server/src/main/java/org/openas2/partner/XMLPartnershipFactory.java#L139

**Comment by uhurusurfa** [comment]
thanks for the feedback.
The message will be updarted to this in the next release:
throw new OpenAS2Exception("Partnership \"" + partnershipName + "\" is missing a node entry for the " +  partnerType + ".");

**Comment by akasparas** [comment]
Thanks!
On a related note, could you please also check that partner node has both name and as2_id attributes defined. Due to spelling mistakes in these names server could not find relationships. And reason for that was very difficult to find.

**Comment by uhurusurfa** [comment]
Message changed in release 3.0.0
