### ISSUE TITLE
Overlapping Zipped Files creates a Zib-Bomb Warning

### ISSUE THREAD

**Issue by igwtech** [OpenAS2/OpenAs2App#281]
https://github.com/OpenAS2/OpenAs2App/blob/9151132176fed3e553954bd7e49bdd67d7fce2e0/Server/pom.xml#L110

This ant-run command creates a Zip file with overlapping files which creates a warning of a Zip-Bomb situation while unpacking.
I suggest it gets reversed

**Comment by uhurusurfa** [comment]
The problem is the "basedir" attribute on the `<zip>` element which is effectively adding a `<fileset>` element for all files then the embedded 2 duplicate that but with the permisions set correctly.
I will remove it for the next release.

**Comment by uhurusurfa** [comment]
Fixed in 3.2.1
