### ISSUE TITLE
config reference value may mistake

### ISSUE THREAD

**Issue by lucifa7** [OpenAS2/OpenAs2App#291]
in release 3.3.0 
the config key smtpauth on tag logger that with classname **org.openas2.logging.EmailLogger**   was with value "$properties.email.auth"
but the key is not defined in this file,the similar key **properties.email.smtpauth** , should I change to that?

**Comment by uhurusurfa** [comment]
😒 ... yes, the attribute in the logger element should be:
`smtpauth="$properties.email.smtpauth$"`

**Comment by lucifa7** [comment]
O(∩_∩)O
