### ISSUE TITLE
run with Mysql 

### ISSUE THREAD

**Issue by lucifa7** [OpenAS2/OpenAs2App#300]
I found that  when I set the msg_tracking.use_embedded_db to false with all other database connection items configed,
the frontPage（vue）get the list of messages stored in mysql using the following command(in class ListMessagesCommand ): 
          >1 DbTrackingModule db =new DbTrackingModule();
          >2 ArrayList<HashMap<String, String>> messages = db.listMessages();
but new DbTrackingModule() get a new empty instance of DbTrackingModule without db configurations,
that produces the Excepion the url is null or cannot get db connection

I try to add a singleton instance to sove that:
 static filed :          >3private static DbTrackingModule instance; 
>4 its getter and setter functions
and set instance at the bottom of function init(...) of DbTrackingModule
>5      setInstance(this);
then change >1 to  
       DbTrackingModule db =DbTrackingModule.getInstance();
and that works .
<img width="959" alt="OpenAS2" src="https://user-images.githubusercontent.com/16380796/192434905-f4aaed04-e285-4058-8472-c51a73526d38.png">

**Comment by lucifa7** [comment]
Would OpenAS2 provide offical solution of Other Database with dialect in the future?

**Comment by uhurusurfa** [comment]
Actually, I see your point. The invocation makes no attempt to use the DB tracking module config.

I will fix that ASAP.

**Comment by uhurusurfa** [comment]
Try the 3.4.0 release - I have not tested it against other RDBMS systems but it is a standard SQL statement so should be good.

**Comment by lucifa7** [comment]
Thank you  to notice me that. I understand that OpenAs2 is  focusing on secure transporting of message over socket.In my case ,I've used OpenAs2 to enable my Application whitch based on data stored in Mysql to communicate with a remote EDIFACT endpoint.I hope my feedback may usefull anway.
