### ISSUE TITLE
What the node && vue version are required for WebUI

### ISSUE THREAD

**Issue by Zero-Xiong** [OpenAS2/OpenAs2App#305]
I failed to build the WebUI locally (but build docker image works). I guess would be the node version and vue version in my PC.

FYI. environment
-----------------------
Windows 11 (22H2)
Node v16.18.1
@vue/cli 5.0.8
yarn v1.22.19
JDK 19 and JDK 17.0.5 both were tried (this one is not related with WebUI)

The error is like:
--------------------------------------------------------
C:\OpenAs2App\WebUI>yarn run serve
yarn run v1.22.19
$ vue-cli-service serve
node:internal/modules/cjs/loader:988
  throw err;
  ^

Error: Cannot find module 'clone'
Require stack:
- C:\OpenAs2App\WebUI\node_modules\defaults\index.js
- C:\OpenAs2App\WebUI\node_modules\wcwidth\index.js
- C:\OpenAs2App\WebUI\node_modules\ora\index.js
- C:\OpenAs2App\WebUI\node_modules\@vue\cli-shared-utils\lib\spinner.js
- C:\OpenAs2App\WebUI\node_modules\@vue\cli-shared-utils\index.js
- C:\OpenAs2App\WebUI\node_modules\@vue\cli-service\bin\vue-cli-service.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\OpenAs2App\WebUI\node_modules\defaults\index.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\OpenAs2App\\WebUI\\node_modules\\defaults\\index.js',
    'C:\\OpenAs2App\\WebUI\\node_modules\\wcwidth\\index.js',
    'C:\\OpenAs2App\\WebUI\\node_modules\\ora\\index.js',
    'C:\\OpenAs2App\\WebUI\\node_modules\\@vue\\cli-shared-utils\\lib\\spinner.js',
    'C:\\OpenAs2App\\WebUI\\node_modules\\@vue\\cli-shared-utils\\index.js',
    'C:\\OpenAs2App\\WebUI\\node_modules\\@vue\\cli-service\\bin\\vue-cli-service.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ChirsGod** [comment]
me too，Have you solved your problem?

**Comment by igwtech** [comment]
I was able to verify successful building of the UI with:

node v19.7.0
vue 2.6.14
yarn 1.22.19

Had to run:
export NODE_OPTIONS=--openssl-legacy-provider && yarn run build

To build, since Node v17+ uses OpenSSL3, which has changed code for initialization context of md family (including md4), and this is a breaking change.

**Comment by ChirsGod** [comment]
> I was able to verify successful building of the UI with:
> 
> node v19.7.0 vue 2.6.14 yarn 1.22.19
> 
> Had to run: export NODE_OPTIONS=--openssl-legacy-provider && yarn run build
> 
> To build, since Node v17+ uses OpenSSL3, which has changed code for initialization context of md family (including md4), and this is a breaking change.

Can you provide the code? I tried to build it locally but it still doesn't work

**Comment by brianpeiris** [comment]
The correct version of node.js is v16. I fixed this Dockerfile_WebUI as well as several other issues with the WebUI in #315

**Comment by brianpeiris** [comment]
I think this can be closed now. Hopefully #315 will resolve this confusion around versions and dependencies.
