### ISSUE TITLE
New Partners not persisted

### ISSUE THREAD

**Issue by apeiris** [OpenAS2/OpenAs2App#319]
When a new partner is added, the information is not being saved to the `partnerships.xml` file. This issue occurs in both the server command line and the WebUI. Although the API post successfully reaches the server (RestcommandProcessor), it fails to update the `partnerships.xml` file.

**Comment by uhurusurfa** [comment]
Closing #329 to be tracked here for resolution.

**Comment by uhurusurfa** [comment]
3.6.0 just released with a fix for this
