### ISSUE TITLE
HowTo document corrections

### ISSUE THREAD

**Issue by jarretttaylor** [OpenAS2/OpenAs2App#337]
In section 14.5. Content Length Versus Chunked (page 60), an XML example is provided. In the example, the property name is incorrect. It should be "no_chunked_max_size" rather than "no_chunk_max_size".

In section 7.9. Custom Mime Headers (page 31), there is a reference to "HTPP headers". That should be "HTTP headers".

**Comment by uhurusurfa** [comment]
Thanks for notifying about the erros.
they have been corrected and will be released in the next version of OpenAS2.
