### ISSUE TITLE
3.6.0 release on GitHub?

### ISSUE THREAD

**Issue by vphantom** [OpenAS2/OpenAs2App#338]
Hello and thank you for continuing to maintain OpenAS2.  In getting my feet wet with OpenAS2 I looked here and at your SourceForge repo.  While there are commits about 3.6.0 here, the "Releases" section only goes up to 3.5.0.  Is the SF version 3.6.0 your actual latest stable release or should I use the 3.5.0 tarball from here?

**Comment by uhurusurfa** [comment]
Sourceforge will alwyas be the most up to date actual release.

**Comment by uhurusurfa** [comment]
However, there is a 3.6.0 release here on Github so not sure where you are looking

**Comment by vphantom** [comment]
The "Releases" feature: https://github.com/OpenAS2/OpenAs2App/releases

When I view that URL, the most recent time is December 26, 2022 for tag `v3.5.0`.

**Comment by vphantom** [comment]
Oh I didn't know; that explains the size difference then. I just got the GitHub tarball and built the Docker image, which was painless. ;)

Thanks for looking into it! I look forward to replacing our current overkill pricey solution with OpenAS2.
