### ISSUE TITLE
WebUI Messages contains timestamps like 2023-28-11 11:54:07

### ISSUE THREAD

**Issue by akasparas** [OpenAS2/OpenAs2App#352]
In these timestamps day and month are swapped. OpenAS2 uses ISOish/military date format in lots of places. So should in this place. Also, I have not seen culture where dates are written in this order (while ISO order is the standard in Lithuania).

https://github.com/OpenAS2/OpenAs2App/blob/71fcd22b7cadc07766a066223e44b950ec851556/WebUI/src/components/MessagesAdmin.vue#L338 also few lines bellow and in commented code.

**Comment by uhurusurfa** [comment]
Closing as the WebUI app is deprecated and will be removed in the near future.
