### ISSUE TITLE
Issue with big files

### ISSUE THREAD

**Issue by stylobille** [OpenAS2/OpenAs2App#36]
Hello,

I just installed openas2 and did some tests on files with sizes of 10-20 MB, this works fine, the files are perfectly send over.

I then tried with a 630 MB file and this doesn't work. I simply put the file in the send folder and it doesn't disappear (I checked, the owner/rights are correct).

So, what I do have, is a file of the same size in the folder pendingMDN3.

All I have in the logs is this :
05/18/17 18:23:18 DirectoryPollingModule: processing /usr/local/apps/as2/bin/../config/../data/topartner/DE_FAFSECFMFI_20170516xxxxxxxxx_0001_16.xml

I checked in the documentation if there is something to change to allow big files, but nothing points to a size limitation.

OpenAS2 is started with the following arguments : 

EXTRA_PARMS="-Xms128m -Xmx2048m -Dorg.apache.commons.logging.Log=org.openas2.logging.Log"

So I guess 2048 MB should be enough for a 630 MB file.

Any idea what I should do to make this work ?

**Comment by stylobille** [comment]
I just tried with a 120 MB files, it went over without a problem, so the limit is somewhere between 120 and 630 MB...

**Comment by uhurusurfa** [comment]
Hi
I just transferred the unzipped 2007.csv file (>700mb) using the latest
release of OpenAS2 : http://stat-computing.org/dataexpo/2009/the-data.html

This was on a Macbook Pro laptop with 8GB RAM and set the Xmx to 6g with
compression enabled for the partnership ( attribute name="compression_type"
value="ZLIB" ).

It did take quite a while (a few minutes) but did do the transfer. If I set
Xmx to 2g I eventually get an out of memory error though this may be
because I am sending the file to the same OpenAS2 instance and therefore
must cache the file for sending and receiving.

**Comment by uhurusurfa** [comment]
NOTE: You may need to set the "readtimeout" attribute on the
AS2SenderModule to a large value if the time taken for the receiving system
to respond to the sent file takes longer than 60seconds. This attribute is
set in milliseconds and the default is 60000

So you would need something like this in the config.xml:
 <module classname="org.openas2.processor.sender.AS2SenderModule"
retries="3" readtimeout="120000">
 </module>

**Comment by stylobille** [comment]
Hello,

Thanks for this precious information.

I just increased the Xmx Value from 2048 to 3072 and this time the processing part finishes pretty quick (less than 15 seconds), so for a 630 MB file 2048MB in Xmx is not enough (good to know).

Now the process hangs, somewhat further with no reason either :

05/23/17 13:13:07 DirectoryPollingModule: processing /usr/local/apps/as2/bin/../config/../data/topartner/DE_FAFSECFMFI_20170516093220071_0001_16.xml
05/23/17 13:13:18 MessageBuilderModule: File assigned to message: DE_FAFSECFMFI_20170516093220071_0001_16.xml [OPENAS2-23052017131307+0200-0f6d0927-2d0b-4f35-b036-91246097bca1@COMPANY-QUA_PARTNER]
05/23/17 13:13:18 AS2SenderModule: message sender invoked [OPENAS2-23052017131307+0200-0f6d0927-2d0b-4f35-b036-91246097bca1@COMPANY-QUA_PARTNER]


I changed the size again from the Xmx from 3072 to 4096 and this time, it goes through without a problem.

I didn't have to change the readtimeout.

Maybe it would be interesting to have a little warning in the logs about memory usage and file sizes, or some lines about this in the documentation, anyway it works for me, so I'm happy, thanks again.

**Comment by uhurusurfa** [comment]
Good feedback - I will certainly add information about large files in the
documentation and look into warning about large files when they are
retrieved for sending.

Feel free to put a review reflecting your opinions on OpenAS2 in
https://sourceforge.net/projects/openas2/reviews
