### ISSUE TITLE
WebUI network error 

### ISSUE THREAD

**Issue by MoaatazElkholy** [OpenAS2/OpenAs2App#360]
Hello, so i ran the docker compose file in the directory, and i keep getting the network error when trying to login with the provided credentials, 
im not sure whats the issue, 
attached below are the logs for both the webUi and the server itself, it seems the request is not passing from the UI to the server as there is nothing related to the request in the server log.

<img width="965" alt="image" src="https://github.com/OpenAS2/OpenAs2App/assets/33905728/99ab639b-0d9d-4392-8a92-89ce6af0dc9c">

<img width="950" alt="image" src="https://github.com/OpenAS2/OpenAs2App/assets/33905728/7b9ae54d-58a6-4126-9d7a-dbecd952d800">

**Comment by mcowart123** [comment]
I am seeing the exact same issue.

**Comment by igwtech** [comment]
Correct, 

The default configuration listens on 127.0.0.1 internally in the docker container of OpenAS2 therefore the docker-compose port exposure doesn't route into it.

I'm creating a pull request to allow the config.xml parameters to be overridden with environment variables on the docker-compose.yml
