### ISSUE TITLE
Embedded database maintenance

### ISSUE THREAD

**Issue by PapaToemmsn** [OpenAS2/OpenAs2App#368]
I was looking around if there's some sort of database maintenance done for the embedded message tracking database but didn't find anything.

What's the intended way to do maintenance tasks for the database (e.g. remove older records)?

**Comment by uhurusurfa** [comment]
Currently there is no strategy.
If you want to add a maintenance module that does record deleting go ahead.

**Comment by mstroming** [comment]
@PapaToemmsn @uhurusurfa

I'm interested in the same thing. In regards to long-term maintenance, it seems like deleting old log files, outbound files and db records are the main ways of maintaining the system long term.

I'm not seeing any mentions of best practices for that anywhere, so I'm curious if you know what people generally do?
