### ISSUE TITLE
Content-Length header isn't populated on synchronous MDN sent after receiving a file

### ISSUE THREAD

**Issue by matt-mcallister** [OpenAS2/OpenAs2App#370]
After receiving a file from a trading partner we are sending a synchronous MDN back to the partner, and everything looks successful from our perspective. However, the trading partner is unable to process the MDN because it is missing the `Content-Length` header. This is causing the trading partner to continuously resend the file since, from their perspective, they haven't received a successful MDN. We recently upgraded from OpenAS2 version v2.14.0, and the header was correctly set in that version.  

This issue exists in version 3.9.1 and 3.10.0.

**Comment by matt-mcallister** [comment]
I confirmed with our trading partner that the changes in this PR resolve the issue 

https://github.com/OpenAS2/OpenAs2App/pull/369

**Comment by uhurusurfa** [comment]
This PR closes this issue: #369
