### ISSUE TITLE
[Feature?] Parsing and Synchronize files to Partners after MDN

### ISSUE THREAD

**Issue by HamzaDevz** [OpenAS2/OpenAs2App#380]
Hello,

Is it possible to add a check if files were properly parsed and synced to partners ?

Shall we develop a new plugin for that ?

Thanks.

**Comment by uhurusurfa** [comment]
You can check the result of any AS2 transaction in the database.
Search these discussions for more info or read the do cumentation:
https://sourceforge.net/p/openas2/discussion/

**Comment by uhurusurfa** [comment]
See section 6.4 "AS2 Message Tracking" in the OpenAS2HowTo.pdf for a discussion of how the database is used to store messages.
