### ISSUE TITLE
Response Code: 411 Length Required  OpenAS2 3.9.1

### ISSUE THREAD

**Issue by rajendramore** [OpenAS2/OpenAs2App#381]
Hello Support,

We are getting below error while sending file to partner in OpenAS2Server-3.9.1.

2024-06-03 13:09:03.591 ERROR AS2SenderModule: Error sending message. URL: http://abc.com/ ::: Response Code: 411 Length Required.

Thank you.

**Comment by uhurusurfa** [comment]
Try searching the discussions here:
 https://sourceforge.net/p/openas2/discussion/

... or read the documentation in the OpenAS2HowTo.pdf and you will find the answer.
