### ISSUE TITLE
Stucks while building WebUI using Docker 

### ISSUE THREAD

**Issue by uzairash** [OpenAS2/OpenAs2App#399]
I am getting stuck repeatedly while building the webUI either with 
`docker build -t openas2_webui:latest -f Dockerfile_WebUI .`
or with docker compose, 
`docker compose build`

it gets stuck on this step 

/ => CACHED [web-builder 2/7] RUN npm install -g --force yarn                                                                                                                           0.0s
 => CACHED [web-builder 3/7] COPY ./WebUI /usr/src/webui                                                                                                                               0.0s
 => CACHED [web-builder 4/7] WORKDIR /usr/src/webui                                                                                                                                    0.0s
 => CACHED [web-builder 5/7] RUN yarn install                                                                                                                                          0.0s
 => CACHED [web-builder 6/7] RUN npx browserslist@latest --update-db                                                                                                                   0.0s
 => [web-builder 7/7] RUN yarn run build                                                                                                                                             118.1s
 => => # yarn run v1.22.22
 => => # $ vue-cli-service build
 => => # -  Building for production...

**Comment by uhurusurfa** [comment]
Have you tried any of these options:
[https://betterstack.com/community/questions/how-to-debug-failed-docker-build-command/](https://betterstack.com/community/questions/how-to-debug-failed-docker-build-command/)
