### ISSUE TITLE
Unable to start OPenAS2 server

### ISSUE THREAD

**Issue by apiplani** [OpenAS2/OpenAs2App#402]
I downloaded OPenAS2 server and configured it on a AWS Linux machine. I am getting an error: 
 Invalid poller module coniguration: [module: null]

No additional help available in logs.

**Comment by uhurusurfa** [comment]
Did you change anything in config.xml or add a properties configuration file?

**Comment by uhurusurfa** [comment]
It looks like you enabled an AS2DirectoryPollingModule but removed the "defaults" attribute. If you are trying to use the generic poller you must use the "format" attribute.
Read the OpenAS2HowTo PDF that comes with the installer.

**Comment by uhurusurfa** [comment]
Closing due to lack of further feedback.
