### ISSUE TITLE
Move the development to github and publish the jar file to maven

### ISSUE THREAD

**Issue by lanxx019** [OpenAS2/OpenAs2App#42]
Github is more community friendly nowadays. And publish the jars to maven would make the project more available to developers.

**Comment by uhurusurfa** [comment]
Are you using the OpenAS2 integrated into your own software?

**Comment by lanxx019** [comment]
It is more or less on the _customization_ side. We are evaluating OpenAS2 as an alternative for our Windows based solution. We'd like to customize OpenAS2 a bit more so it fits into our work flow. Anyhow, publishing OpenAS2 is probably a good idea since it would make customization easier. E.g. I do not need to download the Jar file manually and do not need to check it into my source control. It would also make update easier.

**Comment by uhurusurfa** [comment]
You are welcome to suggest  how you would like to customize the application and will consider whether to incorporate it into the code base. You are also more than welcome to contribute any enhancements back into the code base. Publishing the jar to Maven only makes sense if the application is used as a library and thus far I have not had any indication of others using it this way but if it is actually something that will be useful to the a number of organisations out there I will lokk into adding that step to the release management process.

**Comment by lanxx019** [comment]
I agree with you that application might not have as much motivations to publish the JAR file to maven as a library. IMHO, I think it is useful when you need to customize the behavior of the application and does not necessarily want to push the change to the upstream right away or maybe the use case is too special that it does not make too much sense to ask every one to include your code.

If we push to maven, people can start include the jar as a compile dependency and they can have their customization as source, then they only need to include a configuration file to  enable/disable their customization thanks to the modulation design on OpenAS2.

Sorry about the delayed reply. Let me know if it makes sense.

**Comment by uhurusurfa** [comment]
I have added the ability to deploy to the central repository using Sonatype. This will be published on the next release. Below is a sample of the dependency entry for a Maven build.

`			<dependency>
				<groupId>net.sf.openas2</groupId>
				<artifactId>openas2-server</artifactId>
				<version>2.3.3-SNAPSHOT</version>
			</dependency>
`

**Comment by lanxx019** [comment]
Perfect, thank you! I am going to close this.

**Comment by openas2app** [comment]
Version 2.4.0 release artefacts are now available from the Central
Repository
