### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by gunnicus** [OpenAS2/OpenAs2App#54]
Hi,
I couldn't build this project:

![image](https://user-images.githubusercontent.com/4023477/31523285-462413b8-affe-11e7-8a4b-6e2d48064cbd.png)

![image](https://user-images.githubusercontent.com/4023477/31523294-5380526a-affe-11e7-903b-004b18192653.png)

When I try Maven build it shows me:

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.openas2:openas2-server:2.2.1: Failure to find org.openas2:OpenAS2:pom:2.2.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 3, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.openas2:openas2-server:2.2.1 (C:\ClientStaff\Oban\OpenAS2Server-2.2.1\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.openas2:openas2-server:2.2.1: Failure to find org.openas2:OpenAS2:pom:2.2.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 3, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by uhurusurfa** [comment]
You need to import the base project as well as the Server project.

You end up with package expolrer view looking something like this:
[image: Inline image 1]
You then use the server project for Java code changes to server and the
main parent project provides the key "library" elements that the other
projects use as well.

**Comment by uhurusurfa** [comment]
The easy way to do this is to select the base folder of the OpenAS2 code
base when importing into Eclipse and tick the box that searches for sub
projects.
Once it has fpound the 3 sub projects you can then deselect the remote and
osgi sub projects and you should end up with the correct setup.

On Fri, Oct 13, 2017 at 7:39 AM, Christopher Broderick <uhurusurfa@gmail.com
