### ISSUE TITLE
Option to store raw incoming and outgoing messages

### ISSUE THREAD

**Issue by wilkolazki** [OpenAS2/OpenAs2App#57]
Hi,

I would like to request a feature. 
I would very much like to store raw incoming and outgoing messages. By raw I mean the exact form that was received before any decryption or signature validation and exact form that was sent to other party, after all encryption and signatures were applied. 
I need to store both messages and MDNs. 

If any disputable situation arises, signed and encrypted messages and delivery notifications would be much more reliable proof than just plain messages. Even if we have MDN of sent message, we do not have the message itself, just the content.

It would be best to also have command line tools that could re-validate the received messages and validate that the received successful mdn matches the sent message.

What do you think about this? Or maybe it is possible right now, and I am just missing something?

Best regards,
Szymon Wilkołazki

**Comment by uhurusurfa** [comment]
Currently there is a feature where you can turn mime body part logging on which logs the raw HTTP message to the logs.
It would be easy enough to add a hook at the right place to log the entire HTTP message to a separate file to suit your purposes.

Command line tools to cross validate the stored raw messages would not be too difficult to implement.

I will look to providing that functionality in the next 2-3 months.

**Comment by wilkolazki** [comment]
That would be great, thank you!

**Comment by wilkolazki** [comment]
Hello @uhurusurfa ,

Did you make any progres, or do you have any plans to implement this issue?

Best regards,
Szymon

**Comment by uhurusurfa** [comment]
@wilkolazki - I have not made any progress.... been an extended festive season and only just starting to get back into it. I will be working on it i=over the next few weeks along with some other enhancements and will update you when I am close.

**Comment by uhurusurfa** [comment]
@wilkolazki 
I am looking at implementing this and having spent some time thinking it through in more detail there is a problem with what you are trying to do.

Cross verification will only be possible if the sent messages and MDN's are stored prior to encryption and signing since you would need the partners private key to decrypt the message/MDN and verify the signature.

So given this issue, do you still want the functionality to store the raw messade/MDN?

**Comment by uhurusurfa** [comment]
@wilkolazki  - any thoughts on this?

**Comment by uhurusurfa** [comment]
Closing due to lack of response

**Comment by sdgathman** [comment]
Yes, it is a given that the raw documents will be stored in a real business system.  The MDN includes the MIC of the document, so all OpenAS2 is responsible for is storing the MDN - either the full "raw" MDN, or the MDN with separate detached signature.

Openssl can verify a signed MDN, or MDN with detached signature.  I haven't investigated keytool yet.
