### ISSUE TITLE
OpenAS2 behind a reverse proxy should honor X-Forwarded-For and/or X-Real-IP HTTP headers

### ISSUE THREAD

**Issue by DevDef** [OpenAS2/OpenAs2App#63]
For various reasons (IP sharing, HTTPS offloading…), a reverse proxy could be used in front of an OpenAS2 server. In that case, OpenAS2 is wrongly considering that any remote server initializing an incoming connection is the proxy identified by its private IP address.
It would be useful that OpenAS2 considers the special HTTP headers added by the proxy (`X-Forwarded-For` and `X-Real-IP`) containing the real originator’s IP address.

This would avoid the following issues:
- information about the incoming connection IP addresses in logs are not very relevant;
- the stored message header is also containing the proxy’s IP address as `source_ip` instead of the AS2 partner’s IP address;
- the MDN sent back to the remote server is containing a message with the proxy’s private IP address as the authenticated originator :-(.

Cheers,

Davy

**Comment by DevDef** [comment]
Please see my [pull request](https://github.com/OpenAS2/OpenAs2App/pull/64). This is a first try to better support reverse proxies.

**Comment by DevDef** [comment]
BTW, I wonder why, in the header files, there’s a slash before the value of the IP address for the `destination_ip` attribute…

**Comment by uhurusurfa** [comment]
The slash before IP address is a mystery ...

**Comment by DevDef** [comment]
What about removing it?
