### ISSUE TITLE
Want to move forward

### ISSUE THREAD

**Issue by lucguinchard** [OpenAS2/OpenAs2App#67]
Hello everyone,

I use OpenAS2 for three years, I added several elements to the project in particular database storage in several tables: partner, partnership, as2_message(not with DbTrackingModule) and message_status.
I have not had time to set up database polling yet.

Since I saw that you have recovered the project and you have made nice evolutions :), I’ve tried to merge the sources on https://github.com/lucguinchard/OpenAs2App
I saw that you have also set up the traking for the AS2 messages in a database table. I thought that your method for messages is better, so I deleted mine.

My goal is to make my impovements available to the community.

 Change Log:
1. Better JCE error handling (Java Cryptography Extension)
2. Invalid code in OpenAS2Exception
3. Add a DBFactory class to manage the database (partner and partnership)
4. Adding a database configuration tag for partner & partnership in config.xml
         Sample : 
```XML
<dbconfig url="jdbc:mysql://127.0.0.1/openas2?characterEncoding=UTF-8" user="openas2" password="openas2"/>
<partnerships classname="org.openas2.partner.DBPartnershipFactory" dbconfig="as2_dbA"/>
```
5. Modifying the BasePartnershipFactory class to take into account partners and parnerships outside config.xml
6. Added a DBPartnershipFactory class to search for parnerships and partners in a database.
7. Added Unit tests to test the configuration with the database (environments + createDefaultTable.sql)
8. Support reverse proxies.
9. Cleaning and reformatting the code
10. Take into account a filenameformat in AS2DirectoryPollingModule, to overload the filename.
11. Documentation odt:
        1. Add sample configuration for using Mysql database
        2. Added attribute description : sendfilename and filenameformat

For information, I work with @DevDef 

Thanks,
Luc

**Comment by uhurusurfa** [comment]
Thank you for making this available. I will review and provide feedback when I get a chance.

**Comment by VboxNick** [comment]
Hi Luc,

Thanks for your work. Could you please create a pull request? it will make it faster to review. 

Regards,
nick

**Comment by uhurusurfa** [comment]
If you would like to be a developer on the OpenAS2 project let me know by messaging me from the OpenAS2 Sourceforge site.

**Comment by justanu** [comment]
I am interest end, could you let me know how can I jump in?

**Comment by uhurusurfa** [comment]
Hi justanu ... are you using OpenAS2 and have ideas for enhancing it?

**Comment by justanu** [comment]
Not using currently buy planning to in the near future.And I would like to help.

**Comment by uhurusurfa** [comment]
@justanu - people like Luc above are using the OpenAS2 app and coming up with enhancements that benefit the app. Once you start using OpenAS2 you may identify similar enhancements and then please feel free to code and submit them for inclusion

**Comment by justanu** [comment]
Sure, no problem. I will reiterate my request once I got to know the product better. I've been working on an EDI to XML  translator as a web service and I got a demo working, planning to add the AS2 functionality to it as well. 
In the mean time, keep up the good work.  Thanks all for all your efforts.
