### ISSUE TITLE
MSG_STATE_RECEIVE_EXCEPTION label string error?

### ISSUE THREAD

**Issue by DevDef** [OpenAS2/OpenAs2App#68]
Hello,

The MSG_STATE_RECEIVE_EXCEPTION label string is “Processing exception occurred receiving message. Resend queued.”. I wonder if it makes sense to put an incoming message in resend queue…
I guess it’s an error.

BTW, there are typos in:
- MSG_STATE_MDN_SEND_START label string “Message recieved. MDN sending started.” (recieved →received);
- MSG_STATE_MSG_RXD_MDN_SENT_OK label string "Message received and MDN sent succesfully.” (succesfully → successfully).

**Comment by uhurusurfa** [comment]
Hi
You are correct - that is an error and has been logged for correction
including the typo errors.

Thanks for the feedback.

**Comment by uhurusurfa** [comment]
These corrections will be available in the upcoming version 2.5.0 release
