### ISSUE TITLE
Question regarding supported features

### ISSUE THREAD

**Issue by zharpaz** [OpenAS2/OpenAs2App#78]
Hi,
We consider to use as2-lib and I have a few questions:
What AS2 version does the library supports (1.1, 1.2)?
Does is supports any of the AS2 profiles (http://www.filetransferglossary.com/as2-optional-profiles)?
Was it tested by the Drummond Group certification tests?

Thank you for your help,
   Ziv Harpaz, BMC.

**Comment by uhurusurfa** [comment]
All of your questions are answered on the project page and in the documentation: https://sourceforge.net/projects/openas2/

**Comment by uhurusurfa** [comment]
As for Drummond certification, no it was not tested but it has been running against most if not all the Drummond certified AS2 providers and is a certification in and of itself.
