### ISSUE TITLE
Override app.title

### ISSUE THREAD

**Issue by jvanbaarsen** [OpenAS2/OpenAs2App#82]
Hi,

I was wondering if it's possible to override the app.title? I tried adding `app_title` and `app.title` to the `<Properties>` element in my config.xml, but it seems to be fully ignored.

Can it be that it is because the key includes a `.`?

**Comment by uhurusurfa** [comment]
Why would you want to change the application title?

**Comment by jvanbaarsen** [comment]
@uhurusurfa What do you think would be a fair ETA for the new version? I'm not in an extreme rush, so if the release is scheduled for let's say next month I can wait without problems.

I don't have much experience with the whole java build chain, so I would rather not touch it. But if there is no release planned for the upcoming months, then that's not a problem either and I can try to take a stab at building my own release.

Thanks for taking my concerns seriously 👍

**Comment by uhurusurfa** [comment]
Was hoping to release before end of April but have added scope so will be some time in May now.

**Comment by jvanbaarsen** [comment]
@uhurusurfa No problem. I can perfectly wait until then. Thanks for taking the effort, much appreciated!

**Comment by uhurusurfa** [comment]
Finally just released the latest version with the functionality you wanted to override the user-agent.

**Comment by jvanbaarsen** [comment]
@uhurusurfa Thank you! 👏

**Comment by jvanbaarsen** [comment]
I'll close this issue since feature has been merged in 👍

**Comment by psonon** [comment]
Seems that user-agent is configurable but MDN still sends header "**Reporting-UA: OpenAS2 Server v2.6.3@/A.B.C.D:PORT**" in the "message/disposition-notification" part of multipart/report. I am missing something in configuration?

**Comment by uhurusurfa** [comment]
No you are not missing anything .... I did.
Will make the same change and release a bugfix shortly.

**Comment by uhurusurfa** [comment]
Just released 2.6.4 that should solve your problem

**Comment by psonon** [comment]
Thanks for Reponsiveness! Much Appreciated =b
