### ISSUE TITLE
send messages with different subject to the same partner

### ISSUE THREAD

**Issue by reddevilserbia** [OpenAS2/OpenAs2App#86]
Hi,

Is it possible to have 2 partnerships for partners A and B, but with different Subjects? Also, is it possible to receive messages with different Subjects in separate folders?

**Comment by uhurusurfa** [comment]
Use $msg.headers.subject$ to access the subject string from the inbound MDN
and use it in the "filename" attribute for the storage module something
like this:
    <module classname="org.openas2.processor.storage.MessageFileModule"

filename="%home%/../data/$msg.sender.as2_id$-$msg.receiver.as2_id$/inbox/
*$msg.headers.subject$*
/$msg.content-disposition.filename$-$msg.headers.message-id$"

header="%home%/../data/$msg.sender.as2_id$-$msg.receiver.as2_id$/msgheaders/$date.yyyy-MM-DD$/$msg.content-disposition.filename$-$msg.headers.message-id$"

            protocol="as2"
            tempdir="%home%/../data/temp"/>

**Comment by uhurusurfa** [comment]
For different subjects you should look at the section titled "Setting Dynamic Attributes From File Name" in the OpenAS2HowTo.pdf 
There is a specific example for setting the subject dynamically.
